### PR TITLE
Fix serial call parameter name.

### PR DESCRIPTION
**Pull request by fake-name**
Fix for https://github.com/hgrecco/pyvisa-py/issues/75

### CODE REVIEW

**Comment by fake-name** [comment]
This also fixes another bug with the serial data decoding that I think was probably because the code was never tested under python3k.

**Comment by MatthieuDartiailh** [comment]
@fake-name I fail to see why you decode text_type, should it be encode ? Furthermore six is not a dependency, so we would need to add it.

**Comment by fake-name** [comment]
Yeah, I'm not sure how that worked. It did work, at the time?

Anyways, I no longer have access to the hardware I used to `pyvisa-py`, so I can't really help much. It's been a year and a half!

**Comment by skrchnavy** [comment]
#112 is follower of intended fix. Change in  session.py is related to #66 / #70.

I propose to close this PR without merging.

**Comment by MatthieuDartiailh** [comment]
The issue with timeout parameter is addressed in #112 and the remaining one will be addressed in another PR.

**Pull request closed without merging**
