### PR TITLE
Add missing operations to highlevel.py

### PR DESCRIPTION
**Pull request by aholtzma**
This change plumbs in the missing read_stb() from tcpip.py to highlevel.py.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Could you also add it to sessions.py to return `return StatusCode.error_nonsupported_operation` just like for other methods that may not be implemented by all backends ?

**Comment by MatthieuDartiailh** [comment]
ping @aholtzma

**Comment by MatthieuDartiailh** [comment]
@aholtzma I took the liberty to complete your work and also fix some related issues in tcpip. If anybody can test this on real instruments (I won't have access to any for a week), I would appreciate it.

**Comment by MatthieuDartiailh** [comment]
I tested this and it seems to work. I will merge. Since this was from my point of view the last release blocker, I would appreciate if some people could test before I cut the release. @greyltc @skrchnavy @tivek

bors r+

**Comment by tivek** [comment]
I am sorry for my late reply, I was on the road without the equipment. I can reserve time for later this week to test the new commit.

**Comment by MatthieuDartiailh** [comment]
That would be awesome @tivek. Thanks

**Pull request merged**
