### PR TITLE
fix: allow custom hislip sub_address

### LINKED ISSUE #358: Hislip implementation does not support custom sub addresses
Hislip support was added with version 6.0 (PR #331), but the current pyvisa-py implementation does not allow custom sub addresses in the resource name: the `protocols.hislip.Instrument` class is always used with the default `hislip0` sub address (see [code](https://github.com/pyvisa/pyvisa-py/blob/9b2801269d9aafe8b81745797d2004f02638c731/pyvisa_py/tcpip.py#L136)).

For instance, the following resource names will wait for a response forever during Instrument.initialize:
```
TCPIP::instrument_host_name::hislip_CHASSIS1_SLOT3,4880::INSTR
```
or 
```
TCPIP::instrument_host_name::hislip_CHASSIS1_SLOT3::INSTR
```

I believe this could be fixed by providing the `parsed.lan_device_name` as a parameter to `hislip.Instrument.__init__` and to `hislip.Instrument.initialize`

### PR DESCRIPTION
**Pull request by alxthm**
- [x] Closes #358 
- [ ] Executed ``black . && isort -c . && flake8`` with no errors
- [ ] The change is fully covered by automated unit tests
- [ ] Documented in docs/ as appropriate
- [ ] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Your fix looks fine to me but I cannot test locally beyond the default case. Did you test on an instrument making use of sub addresses ?

**Comment by MatthieuDartiailh** [comment]
You will need to fix the formatting issue before this can be merged.

**Comment by alxthm** [comment]
Thanks for the feedback!

Yes, this has been tested on a different sub address, with and without specifying the port in the resource name:
```
import pyvisa
rm = pyvisa.ResourceManager('@py')
dev = rm.open_resource("TCPIP0::pxi-chassis-01::hislip_PXI0_CHASSIS1_SLOT3_INDEX0::INSTR")
# OR
dev = rm.open_resource("TCPIP0::pxi-chassis-01::hislip_PXI0_CHASSIS1_SLOT3_INDEX0,4880::INSTR")
dev.query('*IDN?')
```

Regarding the formatting issue, it seems to me flake8 is failing on something unrelated to this change. The same issue already appears in [the last release commit](https://github.com/pyvisa/pyvisa-py/actions/runs/4203037863/jobs/7291934034) for instance.
If you wish, I can add a commit that simply ignores the warning (`# noqa: C901`, which seems fair to me in this case), but maybe this would be better as a separate fix?

**Comment by MatthieuDartiailh** [comment]
Sorry for the long delay. I properly fixed the flake8 issue in #362 and fixed a couple of other issues. Could you rebase your work and quickly retest ? Once it is done I will merge quickly.

**Comment by alxthm** [comment]
Done! I can still open resources like before.
Thanks for fixing these other issues :)

**Comment by MatthieuDartiailh** [comment]
Could you add an entry to the changelog ?

**Comment by MatthieuDartiailh** [comment]
Thanks

**Pull request merged**
