### PR TITLE
Unified StatusCode usage

### PR DESCRIPTION
**Pull request by skrchnavy**
Code cosmetic refactoring:
* `StatusCode.<status_code>` replaces `constants.StatusCode.xxx`
* `StatusCode.success` replaces `SUCCESS`.

### CODE REVIEW

**Comment by skrchnavy** [comment]
@MatthieuDartiailh this PR address comment in #116 about `SUCCESS` usage.

**Comment by MatthieuDartiailh** [comment]
Should it be merged after #116 or before ?

**Comment by skrchnavy** [comment]
before #116

**Pull request merged**
