### PR TITLE
usbtmc: enable remote control on USB488 devices

### PR DESCRIPTION
**Pull request by itayperl**
Thorlabs PM101 would not accept any commands without enabling
REN first.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Not sure why ci did not trigger. Let's try using bors

bors try

**Comment by itayperl** [comment]
> ## try
> Build failed:
> 
> * [Check code formatting](https://github.com/pyvisa/pyvisa-py/runs/863577578)

Hmm, the errors seem unrelated to my changes.

**Comment by MatthieuDartiailh** [comment]
I agree. I will try to fix them on master (not sure how they could end up there in the first place) and ask you to rebase once it is done. Otherwise the changes look good.

**Comment by MatthieuDartiailh** [comment]
bors try

**Comment by MatthieuDartiailh** [comment]
Can you run black on your changes ? I took care of the other issue on master.

**Comment by itayperl** [comment]
bors try

**Comment by MatthieuDartiailh** [comment]
Bors try

**Comment by MatthieuDartiailh** [comment]
From the USBTMC 488 specification (http://sdpha2.ucsd.edu/Lab_Equip_Manuals/usbtmc_usb488_subclass_1_00.pdf) your change regarding trigger is incorrect. TRIGGER is a valid MsgID while REN control is a query (along with READ_STATUS_BYTE 128, GO_TO_LOCAL 161 and LOCAL_LOCKOUT 162). 
Furthermore the bit you read regarding capabilities only apply to REN, GO_TO_LOCAL and LOCAL_LOCKOUT but not TRIGGER. I would be nice to store both (rather than `_cap_usb488_states`, I would suggest `_usb488_supports_trigger` and `_usb488_supports_ren` and add a comment describing that it applies also to the other 2 queries). It would also be nice to store the fact that the device is usb488 (`_is_usb488`) since it will let us know if READ_STATUS_BYTE is supported. The relevant bits are described in the mentioned documents.

Can you take care of those changes ? Also can you add an entry to the change log ?

**Comment by itayperl** [comment]
You are correct about TRIGGER, my bad! I added a namedtuple to store the USB488 capabilities more cleanly.

**Comment by MatthieuDartiailh** [comment]
This looks good and I assume you tested locally (I do not have access to right setup et the moment). I just took the liberty to re-phrase the changelog.

bors try

**Comment by MatthieuDartiailh** [comment]
All good ! Thanks for your contribution !

bors r+

**Comment by itayperl** [comment]
Thanks @MatthieuDartiailh, really appreciate the responsiveness!

**Comment by MatthieuDartiailh** [comment]
Thanks ! Trying to do my best on that front.

**Pull request merged**
