### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by jackparmer**
Add a link to Flojoy project (PyVISA-py GUI)

- [ ] Closes # (insert issue number if relevant)
- [ ] Executed ``black . && isort -c . && flake8`` with no errors
- [ ] The change is fully covered by automated unit tests
- [ ] Documented in docs/ as appropriate
- [ ] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by arr-ee** [comment]
Would you care to elaborate?

**Comment by jackparmer** [comment]
Sure thing. Flojoy is building a drag & drop GUI for interfacing with instruments through PyVISA-Py (or PySerial). Examples of instrument connectors already built using PyVISA-Py can be found here: https://docs.flojoy.ai/blocks/hardware/. It seems like there could be something like a "Projects using PyVISA-Py" section on the homepage to help visitors navigate what's available in the growing Python T&M ecosystem.

**Comment by arr-ee** [comment]
There is precious few projects using pyvisa-py, since it doesn’t make sense to use directly — surely you know that.

Seeing a zero-effort advertising PR for a soon-to-turn-non-free project promising “gui” over same old unsafe and non-reusable patterns of access to instruments does exactly fill me with excitement — but that’s just me, of course.

**Comment by MatthieuDartiailh** [comment]
I am not opposed to providing some exposure to flowjoy (since it may benefit PyVISA), however I agree that making it at the level of pyvisa-py makes no sense since it is merely a backend for pyvisa and that I doubt flowjot is re-inventing the PyVISA layer.

**Pull request closed without merging**
