### PR TITLE
sessions: set the default timeout through the API

### LINKED ISSUE #159: TCPIP attribute error
Just recently upgraded to version 0.3.0 and I am seeing the following error:

`
 File "/local/lib/python2.7/site-packages/pyvisa-py/tcpip.py", line 181, in write
    self.link, self._io_timeout, self.lock_timeout,
AttributeError: 'TCPIPInstrSession' object has no attribute '_io_timeout'
`

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
This allows to respect overridden behavior in subclasses.

@Sugarsplash could please test ? I do not have access to a test machine currently

Closes #159

### CODE REVIEW

**Comment by MarcoVogt** [comment]
The initial error seems to be fixed, yet another one appears:

<pre><font color="#008700">In [</font><font color="#4CE64C"><b>1</b></font><font color="#008700">]: </font><font color="#008700"><b>import</b></font> <font color="#0087D7"><b>visa</b></font>
<font color="#008700">   ...: </font>rm = visa.ResourceManager()
<font color="#008700">   ...: </font>dso = rm.open_resource(<font color="#AF5F00">&apos;TCPIP::192.168.10.5::INSTR&apos;</font>)
<font color="#008700">   ...: </font>dso.query(<font color="#AF5F00">&quot;*IDN?&quot;</font>)
<font color="#008700">   ...: </font>
<font color="#AA0000">---------------------------------------------------------------------------</font>
<font color="#AA0000">AttributeError</font>                            Traceback (most recent call last)
<font color="#44AA44">&lt;ipython-input-1-d70f2f85e7e2&gt;</font> in <font color="#1A92AA">&lt;module&gt;</font><font color="#0039AA">()</font>
<font color="#4CE64C"><b>      1</b></font> <font color="#44AA44">import</font> visa
<font color="#4CE64C"><b>      2</b></font> rm <font color="#0039AA">=</font> visa<font color="#0039AA">.</font>ResourceManager<font color="#0039AA">()</font>
<font color="#44AA44">----&gt; 3</font><font color="#AA0000"> </font>dso <font color="#0039AA">=</font> rm<font color="#0039AA">.</font>open_resource<font color="#0039AA">(&apos;TCPIP::192.168.10.5::INSTR&apos;)</font>
<font color="#4CE64C"><b>      4</b></font> dso<font color="#0039AA">.</font>query<font color="#0039AA">(&quot;*IDN?&quot;)</font>

<font color="#44AA44">/home/silab/miniconda2/lib/python2.7/site-packages/pyvisa/highlevel.pyc</font> in <font color="#1A92AA">open_resource</font><font color="#0039AA">(self, resource_name, access_mode, open_timeout, resource_pyclass, **kwargs)</font>
<font color="#4CE64C"><b>   1722</b></font>                 <font color="#44AA44">raise</font> ValueError<font color="#0039AA">(&apos;%r is not a valid attribute for type %s&apos;</font> <font color="#0039AA">%</font> <font color="#0039AA">(</font>key<font color="#0039AA">,</font> res<font color="#0039AA">.</font>__class__<font color="#0039AA">.</font>__name__<font color="#0039AA">))</font>
<font color="#4CE64C"><b>   1723</b></font> 
<font color="#44AA44">-&gt; 1724</font><font color="#AA0000">         </font>res<font color="#0039AA">.</font>open<font color="#0039AA">(</font>access_mode<font color="#0039AA">,</font> open_timeout<font color="#0039AA">)</font>
<font color="#4CE64C"><b>   1725</b></font> 
<font color="#4CE64C"><b>   1726</b></font>         <font color="#44AA44">for</font> key<font color="#0039AA">,</font> value <font color="#44AA44">in</font> kwargs<font color="#0039AA">.</font>items<font color="#0039AA">():</font>

<font color="#44AA44">/home/silab/miniconda2/lib/python2.7/site-packages/pyvisa/resources/resource.pyc</font> in <font color="#1A92AA">open</font><font color="#0039AA">(self, access_mode, open_timeout)</font>
<font color="#4CE64C"><b>    207</b></font>         logger<font color="#0039AA">.</font>debug<font color="#0039AA">(&apos;%s - opening ...&apos;,</font> self<font color="#0039AA">.</font>_resource_name<font color="#0039AA">,</font> extra<font color="#0039AA">=</font>self<font color="#0039AA">.</font>_logging_extra<font color="#0039AA">)</font>
<font color="#4CE64C"><b>    208</b></font>         <font color="#44AA44">with</font> self<font color="#0039AA">.</font>_resource_manager<font color="#0039AA">.</font>ignore_warning<font color="#0039AA">(</font>constants<font color="#0039AA">.</font>VI_SUCCESS_DEV_NPRESENT<font color="#0039AA">):</font>
<font color="#44AA44">--&gt; 209</font><font color="#AA0000">             </font>self<font color="#0039AA">.</font>session<font color="#0039AA">,</font> status <font color="#0039AA">=</font> self<font color="#0039AA">.</font>_resource_manager<font color="#0039AA">.</font>open_bare_resource<font color="#0039AA">(</font>self<font color="#0039AA">.</font>_resource_name<font color="#0039AA">,</font> access_mode<font color="#0039AA">,</font> open_timeout<font color="#0039AA">)</font>
<font color="#4CE64C"><b>    210</b></font> 
<font color="#4CE64C"><b>    211</b></font>             <font color="#44AA44">if</font> status <font color="#0039AA">==</font> constants<font color="#0039AA">.</font>VI_SUCCESS_DEV_NPRESENT<font color="#0039AA">:</font>

<font color="#44AA44">/home/silab/miniconda2/lib/python2.7/site-packages/pyvisa/highlevel.pyc</font> in <font color="#1A92AA">open_bare_resource</font><font color="#0039AA">(self, resource_name, access_mode, open_timeout)</font>
<font color="#4CE64C"><b>   1679</b></font>         <font color="#0039AA">:</font><font color="#44AA44">return</font><font color="#0039AA">:</font> Unique logical identifier reference to a session<font color="#0039AA">.</font>
<font color="#4CE64C"><b>   1680</b></font>         &quot;&quot;&quot;
<font color="#44AA44">-&gt; 1681</font><font color="#AA0000">         </font><font color="#44AA44">return</font> self<font color="#0039AA">.</font>visalib<font color="#0039AA">.</font>open<font color="#0039AA">(</font>self<font color="#0039AA">.</font>session<font color="#0039AA">,</font> resource_name<font color="#0039AA">,</font> access_mode<font color="#0039AA">,</font> open_timeout<font color="#0039AA">)</font>
<font color="#4CE64C"><b>   1682</b></font> 
<font color="#4CE64C"><b>   1683</b></font>     def open_resource(self, resource_name,

<font color="#44AA44">/home/silab/miniconda2/lib/python2.7/site-packages/pyvisa-py/highlevel.pyc</font> in <font color="#1A92AA">open</font><font color="#0039AA">(self, session, resource_name, access_mode, open_timeout)</font>
<font color="#4CE64C"><b>    192</b></font>         cls <font color="#0039AA">=</font> sessions<font color="#0039AA">.</font>Session<font color="#0039AA">.</font>get_session_class<font color="#0039AA">(</font>parsed<font color="#0039AA">.</font>interface_type_const<font color="#0039AA">,</font> parsed<font color="#0039AA">.</font>resource_class<font color="#0039AA">)</font>
<font color="#4CE64C"><b>    193</b></font> 
<font color="#44AA44">--&gt; 194</font><font color="#AA0000">         </font>sess <font color="#0039AA">=</font> cls<font color="#0039AA">(</font>session<font color="#0039AA">,</font> resource_name<font color="#0039AA">,</font> parsed<font color="#0039AA">,</font> open_timeout<font color="#0039AA">)</font>
<font color="#4CE64C"><b>    195</b></font> 
<font color="#4CE64C"><b>    196</b></font>         <font color="#44AA44">return</font> self<font color="#0039AA">.</font>_register<font color="#0039AA">(</font>sess<font color="#0039AA">),</font> StatusCode<font color="#0039AA">.</font>success

<font color="#44AA44">/home/silab/miniconda2/lib/python2.7/site-packages/pyvisa-py/sessions.pyc</font> in <font color="#1A92AA">__init__</font><font color="#0039AA">(self, resource_manager_session, resource_name, parsed, open_timeout)</font>
<font color="#4CE64C"><b>    194</b></font>         attr <font color="#0039AA">=</font> constants<font color="#0039AA">.</font>VI_ATTR_TMO_VALUE
<font color="#4CE64C"><b>    195</b></font>         default_timeout <font color="#0039AA">=</font> attributes<font color="#0039AA">.</font>AttributesByID<font color="#0039AA">[</font>attr<font color="#0039AA">].</font>default
<font color="#44AA44">--&gt; 196</font><font color="#AA0000">         </font>self<font color="#0039AA">.</font>set_attribute<font color="#0039AA">(</font>attr<font color="#0039AA">,</font> default_timeout<font color="#0039AA">)</font>
<font color="#4CE64C"><b>    197</b></font> 
<font color="#4CE64C"><b>    198</b></font>         <font color="#AA0000">#: Used as a place holder for the object doing the lowlevel</font>

<font color="#44AA44">/home/silab/miniconda2/lib/python2.7/site-packages/pyvisa-py/sessions.pyc</font> in <font color="#1A92AA">set_attribute</font><font color="#0039AA">(self, attribute, attribute_state)</font>
<font color="#4CE64C"><b>    407</b></font>         <font color="#AA0000"># First try to answer those attributes that are registered in</font>
<font color="#4CE64C"><b>    408</b></font>         <font color="#AA0000"># self.attrs, see Session.after_parsing</font>
<font color="#44AA44">--&gt; 409</font><font color="#AA0000">         </font><font color="#44AA44">if</font> attribute <font color="#44AA44">in</font> self<font color="#0039AA">.</font>attrs<font color="#0039AA">:</font>
<font color="#4CE64C"><b>    410</b></font>             value <font color="#0039AA">=</font> self<font color="#0039AA">.</font>attrs<font color="#0039AA">[</font>attribute<font color="#0039AA">]</font>
<font color="#4CE64C"><b>    411</b></font>             status <font color="#0039AA">=</font> StatusCode<font color="#0039AA">.</font>success

<font color="#AA0000">AttributeError</font>: &apos;TCPIPInstrSession&apos; object has no attribute &apos;attrs&apos;
</pre>

**Comment by MatthieuDartiailh** [comment]
Sorry for that as I said I do not have a convenient testing system at the moment. The last commit should fix the issue. Please test @MarcoVogt .

**Comment by jake42** [comment]
Works fine here with the second patch.

**Comment by MatthieuDartiailh** [comment]
Thanks for the feedback @jake42 . I will merge then and try to make a bugfix release later this week.

bors r+

**Comment by jake42** [comment]
Great, thanks for your work!

**Comment by MatthieuDartiailh** [comment]
The release is now live on PyPI.

**Pull request merged**
