### PR TITLE
Add support for flush operation (viFlush)

### PR DESCRIPTION
**Pull request by spauka**
This commit adds support for the flush operation, which is already implemented in pyvisa but not in pyvisa-py.

I've also implemented this for the serial interface, for the others, a `NotImplementedError` is thrown, which mirrors what currently occurs.

According to the spec, this method can be implemented for TCPIP and GPIB instruments as well:
http://zone.ni.com/reference/en-XX/help/370131S-01/ni-visa/viflush/

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Thanks for your contribution.  I will try to review ASAP. Do not hesitate to ping me.

**Comment by MatthieuDartiailh** [comment]
This looks good and can be merged. Could you please update the release notes ?

**Comment by spauka** [comment]
Hi @MatthieuDartiailh,
Apologies for the delay. Made changes to the release notes and fixed the merge conflict. Let me know if there are any other issues :)

**Pull request merged**
