### PR TITLE
sessions: pass the timeout value when creating a USB interface.

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
Proper fix for #166 

@mgubser could you please review and test.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
@mgubser thanks for catching this actually I got confused (once again) by the purpose of timeout on session. Hopefully this time I made the explanation clear enough (and got it right). The interface timeout should always be an integer and in ms which is why I reassign the default value after creating the interface rather than simply converting to int as you suggested in #168 . Please check this fixes your issue.

**Comment by mgubser** [comment]
@MatthieuDartiailh This looks ok now. I don't see any related errors anymore. Thanks for taking on this issue.

**Comment by MatthieuDartiailh** [comment]
Thanks @mgubser. I will update the release notes and merge sometime this week.

**Pull request merged**
