### PR TITLE
use and document gpib-ctypes

### PR DESCRIPTION
**Pull request by tivek**
related to #137 #105

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
May be worth adding a mention in the docs too.

**Comment by tivek** [comment]
I'll just make one more quick test on Windows and confirm during the day.

**Comment by tivek** [comment]
> May be worth adding a mention in the docs too.

Right. Will do.

**Comment by tivek** [comment]
I'm happy with the change. If you agree, I think it is ready.

**Comment by MatthieuDartiailh** [comment]
I made a minor fix to the docs. Merging.

**Pull request merged**
